language: r
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.cache/hdf5
    - $HOME/R/Library
before_install:
- source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
- install_hdf5
install:
- install_cran devtools covr pkgbuild
- install_withdeps
after_success:
- R -e 'covr::codecov()'
