language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
env:
  - R_MAX_NUM_DLLS=250
install:
 - R -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
 - R -e 'devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
