language: r
sudo: required
dist: trusty
os:
 - linux
 - osx
cache: packages
install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libgit2; fi
 - R -e 'if ("devtools" %in% rownames(installed.packages())) update.packages(oldPkgs = "devtools", ask = FALSE) else install.packages("devtools")'
 - R -e 'devtools::install_cran("covr")'
 - R -e 'setRepositories(ind = 1:4); devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
after_success:
 - R -e 'covr::codecov()'
